# Generated by Django 5.0.4 on 2024-04-19 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_dealers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=100)),
                ('c_phone', models.CharField(max_length=10)),
                ('c_email', models.EmailField(max_length=254)),
                ('booking_date', models.DateField()),
                ('booked_on', models.DateField(auto_now=True)),
                ('deal_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.dealers')),
            ],
        ),
    ]
